git:
  depth: 10

language: c

matrix:
  include:
    - name: "Ubuntu 16.04 / GCC"
      os: linux
      dist: xenial
      compiler: gcc
      env:
        - CFLAGS='-Wall -Wextra'
        - CPARAMS='--enable-werror'
    - name: "Ubuntu 16.04 / Clang"
      os: linux
      dist: xenial
      compiler: clang
      env:
        - CFLAGS='-Weverything -Wno-padded'
        - CPARAMS='--enable-werror'
    - name: "Ubuntu 18.04 / GCC"
      os: linux
      dist: bionic
      compiler: gcc
      env:
        - CFLAGS='-Wall -Wextra'
        - CPARAMS='--enable-werror'
    - name: "Ubuntu 18.04 / Clang"
      os: linux
      dist: bionic
      compiler: clang
      env:
        - CFLAGS='-Weverything -Wno-padded'
        - CPARAMS='--enable-werror'
    - name: "Ubuntu 18.04 / Clang Sanitizers"
      os: linux
      dist: bionic
      compiler: clang
      env:
        - CFLAGS='-O1 -g -fsanitize=address -fsanitize-address-use-after-scope -fno-omit-frame-pointer -fsanitize=undefined -fsanitize=nullability -fsanitize=implicit-conversion -fsanitize=integer -fsanitize=float-divide-by-zero -fsanitize=local-bounds'
        - ASAN_OPTIONS=strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1
        - UBSAN_OPTIONS=print_stacktrace=1:print_summary=1:halt_on_error=1
        - CPARAMS='--enable-werror'
    - name: "Ubuntu 18.04 / Clang analyzer"
      os: linux
      dist: bionic
      compiler: clang
      env:
        - COMPILER=scan-build-10
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-10
            - clang-tools-10
            - libsqlite3-0
            - libsqlite3-dev
            - libgd3
            - libgd-dev
            - check
    - name: "OS X / Clang"
      os: osx
      osx_image: xcode11
      compiler: clang
      env:
        - CFLAGS='-Weverything -Wno-padded -Wno-reserved-id-macro -Wno-gnu-zero-variadic-macro-arguments -Wno-sign-conversion -Wno-unreachable-code -Wno-missing-noreturn'

addons:
  apt:
    packages:
      - libsqlite3-0
      - libsqlite3-dev
      - libgd3
      - libgd-dev
      - check
  homebrew:
    packages:
    - gd
    - sqlite
    - check

script:
  - |
    if [[ "${COMPILER}" =~ ^scan-build.* ]]; then
      ${COMPILER} -analyze-headers --status-bugs ./configure --enable-werror --disable-silent-rules
      ${COMPILER} -analyze-headers --status-bugs make
      export TRAVIS_TEST_RESULT=$?
      travis_terminate $TRAVIS_TEST_RESULT;
    fi
  - ./configure ${CPARAMS} && make check || ( cat test.log ; cat test-suite.log ; exit 1 ) && ./vnstat --version && grep -iP 'sanitizer|runtime error' check_vnstat.log && exit 1 || true

notifications:
  email:
    on_success: always
    on_failure: always
